logging:
  level:
    org.springframework: DEBUG

security.filter-dispatcher-types: ASYNC, FORWARD, INCLUDE, REQUEST, ERROR # this is necessary due to some bug in actuator that puts /error in a different filter chain.